### ISSUE TITLE
Can’t remove or override bottom margin class on error panels

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1568]
Can’t adjust bottom margin class on error panels

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1385#discussioncomment-897716_

**Comment by yatesn** [comment]
Part of spacing work - not currently a priority

**Comment by adi-unni** [comment]
When multiple components are met with each other, the spacing is taken over by _spacing.scss and the margin tops are preset to 1.5 rem. No setting is happening between different components individually, within their respective component css. The issue is specifically regarding example-select-with-error, but there is no margin being placed on that either.
