### ISSUE TITLE
The description on an input with suffix/prefix prevents the `title` being read out on Mac VoiceOver

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1581]
The description on an input with suffix/prefix prevents the `title` being read out on Mac VoiceOver

So the user does not hear the units required for the input.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/279#discussioncomment-955751_

**Comment by willcAND** [comment]
After some investigation into this, it looked like the label was not actually being read out correctly - on mac voiceover. This behaviour only happens when an input is prefixed/suffixed. Implemented a fix for this which allows the user to access a more options menu on voice over, reading out the units required.
