### ISSUE TITLE
Back to top link

### ISSUE THREAD

**Issue by JovdP** [ONSdigital/design-system#1599]
## What

Back to top link component

## Why

To Enable users to get back to the table of contents at the top of the page

> Explain why you think this feature or content should be added to the ONS Design System.
>
> - What evidence do you have that your ONS service needs it?
> - What evidence do you have that it meets the needs of the users of that service?
> - Have you checked if it’s already in the ONS Design System?
> - Have you considered creating a new variant of an existing feature instead of something new?

## Supporting material

Research from 2018 prototypes (DP to provide)

> Include links to any examples, research, prototypes or code that support your proposal.

## Contacts

> The Design System working group has a weekly meeting. We will invite you to one of these meetings to give a show and tell about your proposal and answer any questions. Please tell us who to invite to that meeting. We recommend involving at least your product manager, user researcher and designer.

Display: Take users back to top

**Comment by armstrongb** [comment]
Current 'default state' of the back to top link:
![BackToTop-base](https://user-images.githubusercontent.com/22910336/126503379-25772e12-25e9-4763-b4de-fd8af559ed86.png)
>A key line was added based on research conducted around Area Profiles. The key line helps to highlight the navigation item.

Originating designer: Will Richards
Source file: Figma
Page context used in research (attached)

![DatasetLandingPage-996](https://user-images.githubusercontent.com/22910336/126504252-d82bba33-69f6-4ddd-841b-a2c61013afeb.png)

**Comment by jrbarnes9** [comment]
@armstrongb Do you think this link could be "sticky" to avoid the visual repetition? I think we could probably still ensure it's focusable after each content block.

**Comment by emilymaylawes** [comment]
Accessibility considerations:
- Must be an anchor link that targets an anchor # to the top of the page. Either the <h1> of the page or the <main> content (alternative to skip to content). In that case, keyboard focus is managed.
- Must be the last link of the <main> content so right at the end of the focus order.
- If sticky to the bottom or anywhere on the page, must not obscure any other content on all screen viewports and not obscure focus.
- Must not rely on JavaScript
- Should only have one on the page, rather than repeated
- If `scroll-behaviour` property in CSS is used, ensure we turn this off with `@prefers-reduced-motion` media query

**Comment by adi-unni** [comment]
#### Technical side:

- It can be added as an overlay by adjusting the z-index
- It can be added as a component to be added at the bottom of the page
- It can be added to fit within the page contents on the navigation sidebar
- Behavior can be modified depending on zoom level. If zoom is too high and nav sidebar disappears, then button can be moved to main content block

Dev Note: Adjusting the behavior to be controlled based on the presence of @media content max-width class

Any dynamic behavior can only be enabled through javascript. If javascript is enabled:
- component could be floating on the page
-  hidden/revealed depending on the where the user is scrolled to on the page
	scrollable

Accessibility:

Keyboard users can already reach the top by tabbing at the end of the page or pressing the home button, unless they are in a text entry box. Does it meet accessibility requirement: https://www.w3.org/WAI/standards-guidelines/act/rules/0ssw9k/proposed/ if this is the case.

Needs to be compatible with VoiceOver when used and is not hidden i.e. when the user has scrolled more than 4 screens down the webpage and the button becomes available to click.

Further considerations:

- Link styled as a button/button or as styled as a link/link
- Primary location / (optional) secondary location
- If the button is an overlay, will it be transparent/ translucent , or otherwise. Adjusting transparency may make it more visible when covering other content
- Will the button be visible all the time, when user has scrolled to a particular or only at the end of the page

NNG recommendations are for the button to be placed in the bottom right as this is where the users expect it to be. Implication is for it to be hovering over content.
https://www.nngroup.com/articles/back-to-top/

Other Versions:
Intelligence community DS:
[https://design.sis.gov.uk/components ](https://design.sis.gov.uk/components)(Button is a floating component featured in the bottom right)
Scottish Gov DS:
https://designsystem.gov.scot/components/back-to-top (Button is a floating component found in the bottom right)
Gov UK DS:
https://design-system.service.gov.uk/components/back-link/#top (Button is a floating component found in the sidebar navigation - on magnification 400%, it merges with main content block

**Comment by Majsol** [comment]
https://www.ons.gov.uk/economy/grossdomesticproductgdp/bulletins/quarterlynationalaccounts/apriltojune2023
https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice

**Comment by yatesn** [comment]
Decision on next steps needed - Joe and Dina to review

**Comment by Majsol** [comment]
There are several products interested in implementing the "back to top" component so the considerations above will be presented at the design crit session on tuesday... and hopefully we will reach a decision that accommodates most products.

**Comment by Majsol** [comment]
Waiting for feedback from IDS (Alan and Aurora)

**Comment by JNATION85** [comment]
Can we go ahead with the development that Adi has done.

**Comment by adi-unni** [comment]
Display - Building a back to top button

**Comment by JNATION85** [comment]
Need to get some content and page structure to preview on the DS

**Comment by daniellecorke** [comment]
Content design request added to the UCD centralised backlog.

**Comment by adi-unni** [comment]
Changes to width of the BTT button are currently set to the width of the last sibling element in the HTML e.g. if the element above it is a grid, then the width will match that. Here are a couple examples of this behaviour:

<img width="1680" alt="Screenshot 2024-02-26 at 11 39 25" src="https://github.com/ONSdigital/design-system/assets/56112669/93c6c158-1848-4c76-a738-8aac27e571f0">

When the window is smaller, the highlighted section looks like this:

<img width="739" alt="Screenshot 2024-02-26 at 11 40 26" src="https://github.com/ONSdigital/design-system/assets/56112669/c4ebd961-056f-4b44-bf2a-c1ba054449bc">

The proposed change would make the highlighted state look like the skip to content header when highlighted i.e full page width. Here are some examples of this:

<img width="1792" alt="Screenshot 2024-02-26 at 11 57 03" src="https://github.com/ONSdigital/design-system/assets/56112669/d3ef4a06-fdcc-4531-8707-6f4262df8cc4">

With a similar look on smaller pages:
![Screenshot 2024-02-26 at 12 06 32](https://github.com/ONSdigital/design-system/assets/56112669/5262d4d9-465a-45e1-9727-0a36f2b90c31)

However on larger window sizes the look of the button looks like this:
![Screenshot 2024-02-26 at 11 58 36](https://github.com/ONSdigital/design-system/assets/56112669/6a23dc8d-e432-4a81-b66f-5275b0c0c741) 
as compared to this:
![Screenshot 2024-02-26 at 11 57 49](https://github.com/ONSdigital/design-system/assets/56112669/f71dc7a9-bfab-47e3-a449-479b7ca97382)

From a UX standpoint, what would be the best thing to do here @JNATION85 @Majsol ?
