### ISSUE TITLE
search-index.json file should be updated when running yarn start

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#1763]
Currently search-index.json doesn't get updated when running the DS locally with `yarn start`. It only gets updated when running `yarn build`.
If we make a change to update it also when running `yarn start` it will be more up to date when running locally. We can then remove search-index.json from the repo, because it is a file that is created dynamically when running the DS it doesn't make sense for it to be checked into git.

**Comment by kruncher** [comment]
> Currently search-index.json doesn't get updated when running the DS locally with yarn start. It only gets updated when running yarn build.

The `build/search-index.json` file is initially updated when running the `yarn start` command. To verify this:
1. Delete the 'build' directory.
2. Execute `yarn start`.
3. Observe that the `build/search-index.json` file now exists.

> We can then remove search-index.json from the repo

The 'build' directory is excluded from the git repository in `.gitignore` so the `build/search-index.json` file should not be seen as a working change by git.

There is a placeholder file at the path `src/search-index.json` which acts as a seed for generating the real search-index.json as a part of the gulp task.

I have replaced the contents of this stub file with a comment documenting it's purpose rather than having it contain search index data (see https://github.com/ONSdigital/design-system/pull/1987).
