### ISSUE TITLE
Add documentation for "Address" pattern

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1969]
https://ons-design-system.netlify.app/patterns/addresses/

Consider adding postcode only variant of pattern (used in RH census 2021)

Add reference to a new "addresses" style that documents how an address should be presented (see attached [trello card](https://trello.com/c/UI8PDAJN/542-issue-800-define-how-postal-address-should-be-marked-up-displayed))

Linked to #413 and PR #1514

**Comment by jrbarnes9** [comment]
Added to content design epic: https://trello.com/c/1wBGbk9Q/569-epic-design-system-patterns-where-there-is-little-or-no-documentation-or-it-needs-a-review

**Comment by OscarJackson** [comment]
https://trello.com/c/a4L4cFhe/664-design-system-addresses

Raised a couple of concerns on my Trello board:

@joenation3 This seems like more of a component than a pattern as you’d only use one of the variants (rather than any of them in combination.

I can update the address component with;

address confirmation variant
a note about using the footer variant with crown copyright if the address index API is used as per [Add warning to use footer variant when using address input with ONS Address Index API · Issue #1112 · ONSdigital/design-system](https://github.com/ONSdigital/design-system/issues/1112)
‌

But not sure if there’s additional work needed re' the postcode only variant: [Add documentation for "Address" pattern · Issue #1969 · ONSdigital/design-system](https://github.com/ONSdigital/design-system/issues/1969)

Or what’s meant by this: https://github.com/ONSdigital/design-system/issues/1953

**Comment by daniellecorke** [comment]
Screenshot of CD Trello (no longer available):
![image](https://github.com/ONSdigital/design-system/assets/102512949/4f55a229-33e1-4e7f-b4e6-a1c1e7f239cf)

**Comment by daniellecorke** [comment]
Blocked until the outcome of #3032.

**Comment by daniellecorke** [comment]
Documentation updated as part of #3032.
