### ISSUE TITLE
Improve "Links" style

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1980]
- Link style (hover, visited etc), external links, accessibility etc.

- Add to typography

- Add style guide for using links in content e.g. https://www.gov.uk/guidance/content-design/links

- Enable implementation of descriptions for screen readers and add documentation on linking to external websites and opening in a new window/tab.

Also add external link guidance including warning users (with text) when an link will open in a new window (web chat example)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/233#issuecomment-641815117_

**Comment by kruncher** [comment]
In addition it would be nice to simplify the following things:
- Simple parameter to specify that link should open in a new window (instead of having to manually specify `rel` and `target`).
- Automatically detect when the URL is an external one (compare with list of internal domains, and relative URLs are always internal for when no protocol is provided in the URL).

**Comment by yatesn** [comment]
Variant exists so no longer needed
