### ISSUE TITLE
[Bug]: V3 not optomised for mobile - links hidden

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2033]
### What happened?

It seems that V3 is not optomised for mobile as the links at the very top disappear. Due to go live on 26th Mar 

### What was the expected outcome?

That the full page would be visible when using a mobile device

### How is this problem impacting your service?

Navigation issues for users

### What list of steps can be followed to reproduce the bug or issue?

View V3 pages on a mobile device

### Example

![image](https://user-images.githubusercontent.com/97620554/157270865-40ffd6ae-cb75-421d-8387-8a8b50c63a26.png)

### What version of the ONS Design System are you using?

Unsure

### What devices are you seeing the problem on?

- [ ] Desktop
- [X] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by jrbarnes9** [comment]
These should probably be displayed in the collapsed mobile menu.  

Consider also allowing one link to be set as fixed in masthead so always accessible in one click e.g. 'Sign out'.

Consider whether the 'save and sign out' CTA also be displayed in the menu alongside the service links rather than the footer as it currently is?
