### ISSUE TITLE
Document macro options in a consistent way across all components

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2076]
The following components do not include a `_macro-options.md` file:

- ~call-to-action~
- error
- field
- fieldset
- icons
- ~modal~
- ~promotional-banner~
- ~quote~
- ~text-indent~
- ~timeline~
- ~video~

**Comment by jrbarnes9** [comment]
I have struck through the components that I added separate `_macro-options.md` files for in #2126.

The remaining components don't have examples or documentation, which is why their macro options are not in separate files and some are documented in tables in their `index.njk` file instead (otherwise they wouldn't visible on the website).  

But we might want to consider a way to pull through markdown files into the website?

**Comment by daniellecorke** [comment]
Closing this ticket to investigate #3158.
