### ISSUE TITLE
Review semantic tag used for highlighting

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2093]
I think `<strong>` or `<b>` would be more suitable for [highlighting](https://ons-design-system.netlify.app/foundations/typography/#highlighting) as we’re using it to distinguish importance and draw attention, and not to change the meaning of a sentence with stressed emphasis.

> The `<strong>` [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element indicates that its contents have strong importance, seriousness, or urgency

_https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong_

> The `<strong>` element is for content that is of greater importance, while the `<b>` element is used to draw attention to text without indicating that it's more important.

_https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong#b_vs._strong_

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/233#discussioncomment-2451492_

Useful info: https://www.tempertemper.net/blog/bold-and-italics-arent-read-by-screen-readers

**Comment by yatesn** [comment]
mark element

**Comment by armstrongb** [comment]
It might be worth considering that there times where `<em>` seems to make sense in adding emphasis as the highlight is being used to draw visual attention to something that has changed (e.g. one element of question where the stem of the question remains the same) so adding stressed emphasis is treating AT users with equity.

Maybe highlight should be available for for multiple elements but with clear explanation about the context for their use?

**Comment by jrbarnes9** [comment]
There are accessibility concerns for both many of these inline emphasis tags, because few screen readers announce them by default. DAC have suggested prefixing with visually hidden text (similar to what we do with panels) if we want to ensure a consistent announcement.

**Comment by emilymaylawes** [comment]
I believe we have two distinct options and use cases here, and I raise an argument, similar to @armstrongb above, that we could provide different variants of this component but provide **clear instructions** as to when each can be used. This could be within the nunjucks macro to provide either 'strong' or 'mark' as a value which will modify the outputted HTML. This does raise some concerns as to why we are using different underlying HTML but visually styled identically. In this case, we likely have a case to make a different style entirely for the different use cases.

I believe the `<em>` tag should not be used due to it only being used to modify meaning within the text as to which word is stressed.

By default, the highlighted text should be wrapped with a `<strong>` tag which implies emphasis on the 'importance' of the word itself within the sentence.

However, the Service Manual itself highlights a use case "It can be used to indicate a calculated or piped value which was entered previously by the user and is being displayed in a new context.". This is a good example of where a `<mark>` element should be used as that is the semantic equivalent of 'relevance' in context.
"Otherwise, `<mark>` indicates a portion of the document's content which is likely to be relevant to the user's current activity. This might be used, for example, to indicate the words that matched a search operation."
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark#accessibility_concerns
However, as Jon mentioned above, it is important to ensure this works for assistive technology so the prefixing suggestion with screen reader only text is a valid solution. See the [panel component](https://service-manual.ons.gov.uk/design-system/components/panel#example.example-panel-with-information.html) for the screen reader only text before the panel to indicate the colour used. We could prefix with "Your inputted value", or similar.

It is likely safest to fall back to using a `<strong>` tag. However, if it's purely used for styling, we should be using an entirely semanticless tag `<b>` or `<span>`. Due to this, documentation and advice here is likely a preferred next step combined with the user freedom to pick the semantic tag that works for them; however, this raises questions of the need for more stylistic typography for the different semantic inline text tags.

@alec-hamilton-ons  will raise this at standup tomorrow, but food for thought.

**Comment by emilymaylawes** [comment]
Interesting to note:
"No browsers expose strong or em element role semantics in the accessibility tree."
So actually, `<mark>` would even be better support than `<strong>` for screen readers/AT even if it's not fully there yet.
But again, needs to only be used when relevant to previous context, rather than 'important'.

**Comment by emilymaylawes** [comment]
I am happy to suggest we update all `<em>` tags to `<strong>`.

Down the line, an enhancement to allow the users to decide whether the semantic tag should be `<strong>` or `<mark>` could be implemented.
