### ISSUE TITLE
Checkboxes label should not be required for nested checkboxes

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2351]
It's likely the legend for the checkboxes will also include the hint that would normally be displayed in checkboxes label 

For example, 
> Select your preferred times of day
> - [ ] Any time of day
> - [ ] Morning

Rather than, 
> **Preferred times of day**
> Select all that apply
> - [ ] Any time of day
> - [ ] Morning

Also, if checkboxes are nested within checkboxes, then the parent checkbox label should provide necessary context and not be required to be repeated. 

----

> > `checkboxes__label` is rendered when not set...
> > ![Screenshot 2022-07-21 at 15 47 16](https://user-images.githubusercontent.com/43346934/180244316-d8b71550-fef6-4e93-958b-27f36d4d6920.png)
> 
> ![Screenshot 2022-07-21 at 16 04 21](https://user-images.githubusercontent.com/42928680/180247533-1db51dd3-5168-417d-8c0c-35ac066c2bd4.png) Its required to be set

Oh yeah I can see now that issue is on the main branch. Probably explains why the margin was removed from the nested legend then.  I'll raise a separate ticket.  I don't think we'd need both legend and label for nested checkboxes

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/2329#issuecomment-1191619514_

**Comment by precious-onyenaucheya-ons** [comment]
Since the checkboxlabel and the legend both provides context to the component. I have made the checkboxlabel to be required only when the legend is not provided.

This is the current implementation


![Image](https://github.com/ONSdigital/design-system/assets/86783201/edcd5711-a1a3-499c-9593-3d0c5e108f7d)



And it also fixes the issue with repeated context 


![Image](https://github.com/ONSdigital/design-system/assets/86783201/07e99c1c-0f06-4237-9143-e792537d0d04)
