### ISSUE TITLE
Investigate the use of djLint

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2760]
djLint is a code linter and formatter that we are currently looking at implementing in eQ. I think it would be worth looking at for the DS too. Will help us keep our HTML and Nunjucks files linted and formatted.

https://www.djlint.com/

**Comment by adi-unni** [comment]
Whilst the tool is very versatile, it isn't correct consistently. It can easily be set up with pyproject.toml and running the the tool is very simple, by running djlint path-to-file check. However it often formats a lot of code incorrectly within the design system, particularly when calling components, removing tabbing and decreasing readability, rather than increasing, An example of this is when running it over the card with list component. Similar findings have been voiced by the eQ investigation of the tool: https://trello.com/c/4tEwAbMs/5436-investigate-djlint-html-jinja-linter-formatter and further details about its compatibility with Jinja can be found there.

**Comment by rmccar** [comment]
I have also had a look into the implementation of djlint and when running it for files it doesn't seem to recognise .njk files. I have a raised an [issue](https://github.com/djlint/djLint/issues/810) on the repo because of this and because of this and the issues above at the moment this doesn't seem to be an option for us. If these issues get resolved we can have another look into implementing it
