### ISSUE TITLE
Page sections should have anchor links in the titles

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2881]
This is a suggestion that has been raised before so there might be another card for it but we should have anchor links on our section titles on pages so that users can link to a specific part or example on a page.

This might be something that we want to go through design on what we want the links to look like. There is currently ids on all our titles so the link can be created manually by the user but it would be good to make the titles clickable so that it would be easier for the user to get the link they need to refer to a specific part of a page.

**Comment by adi-unni** [comment]
### Placement:
**Positioning:**

- Put the "Copy Link" button in close proximity to the heading it relates to.

Consistency:

- Placing button on the right introduces variable change for the location of the button according to title length. 
- Placing button on the left raises a lot of technical considerations and doesn't look right in terms of placement, but is consistent in location

### Visual Design:

- Clear text like "Copy Link" for easy understanding of buttons purpose
- Use an icon (like a chain link) alongside the text to visually represent the action.

**Tooltips:**

- If additional information is required. Implement a tooltip that appears when users hover over the "Copy Link" button. The tooltip can provide additional context. 
- This could be flipped to reduce visual clutter. The actual button could be just an icon, but when hovered/focussed state, a tooltip could appear

**Feedback:**

- Changing the button colour briefly to a darker shade or ons blue indicating its been clicked. Consider changing text from "Copy Link" to "Link Copied" with a tick icon

   _(dev note: that functionality can only be done with javascript. Response with javascript disabled could still have the colour 
    change but no change of text)_

**Responsiveness:**

- Considerations on button size and placement in mobile screens (whether again it needs text or not)
- Since mobiles have neither focused or hover states, it may be better to have the text upfront and an icon rather than hiding the text behind a tool tip

### Accessibility: 

**Keyboard Accessibility:**
- Needs to be in the tab index

**Focus States:**

- Clear focus states

**ARIA Attributes:**

- Use specific aria attributes for specific headers? "Copy link to heading: ....." 

Examples (for visual design) :

https://kinsta.com/blog/anchor-links/#step-3 

https://learn.microsoft.com/en-gb/power-platform/alm/overview-alm?WT.mc_id=DX-MVP-5004113#what-is-alm
(icon only appears and on the left when user hovers over the title)

https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html
(similar to the one above)

https://docs.github.com/en/get-started/learning-about-github/githubs-plans#github-team
(github docs to the right)

**Comment by Majsol** [comment]
@JNATION85 and I had a chat about this and decided we won't go ahead with the anchor links. The users can simply use the functionality that is already provided by marking some text, right clicking and then select the option "copy ink to highlight"

**Comment by daniellecorke** [comment]
@Majsol @JNATION85 can I close this ticket?

**Comment by daniellecorke** [comment]
Closing this ticket as it duplicates #1879 which has been moved to the UCD Board.
