### ISSUE TITLE
H4 headings are the same at the base font style, so it's impossible to differentiate between a paragraph and an h4 heading.

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#379]
H4 headings are the same at the base font style, so it's impossible to differentiate between a paragraph and an h4 heading.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/233#issuecomment-492765445_

**Comment by bameyrick** [comment]
This was originally the case with h5 headings, but was always overriden with a utility class to set it to bold at base font size. That currently the default for a h3, so I'm not sure what we should do with h4s? Make them the same as h3s? 

Maybe we need to look into reducing the steps between different font sizes so that `u-fs-xl` is currently the same size as `u-fs-l` and then we step down the remaining sizes to `u-fs-r` evenly?

**Comment by jrbarnes9** [comment]
@will-madebymoon @bameyrick Content designers have also raised concerns about h3's not being prominent enough on the page.

**Comment by bameyrick** [comment]
h1's have always been `u-fs-l` in eq-runner due to the length of questions, and because the design system only really was for runner before thats what h1's have been set to as a default, but now that we have more products coming on to the design system h1's being `u-fs-l` might not be the correct default for everything.

It might be that we need to set headings to default to:
h1: `u-fs-xl`
h2: `u-fs-l`
h3: `u-fs-m`
h4: `u-fs-r--b` 

and then have the question component (which wraps the question in a h1) override the default and set the question h1 to `u-fs-l`.

**Comment by jrbarnes9** [comment]
I agree with Ben

**Comment by will-madebymoon** [comment]
Actually I think most pages should use the same H1 for continuity. If we have variations this will look odd as you traverse through the different products. Most pages will use a hybrid of u-fs-l

**Comment by bameyrick** [comment]
If we don't want to increase the size of h1's, how about we change the utilities and defaults for headings to be something more like this?

Heading | Utility Class | Pixel Value 
---------|-------------|-----------
n/a          | u-fs-xxl        | 36px
h1            | u-fs-xl          | 28px
h2           | u-fs-l            | 24px
h3           | u-fs-m          | 22px
h4           | u-fs-r--b       | 18px

**Comment by will-madebymoon** [comment]
This makes sense

**Comment by jrbarnes9** [comment]
Sound good.  Think we need to sort the spacing out too - think headings need some top margin (if not first)
