### ISSUE TITLE
Search component

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#656]
Use this issue to discuss the search(https://ons-design-system.netlify.com/components/search) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by matthewandrewpalmer** [comment]
For the Character check Variant of the search component, would it be possible to have a variant that either had a range or just a limit check. 

In the Blaise survey manager, we have a search by serial number which is a minimum of 8 characters but it could be up to 11 characters.

**Comment by boxadesign** [comment]
Yes this wouldn't be a problem. Are you happy to do this work and raise a PR?

**Comment by matthewandrewpalmer** [comment]
@boxadesign I have implemented this with a parameter to only check against that the input is at least the required length and i've updated the documentation. Would be good if you could have a look at it, I can't push or create a PR as I don't have access.

**Comment by trevorsaint** [comment]
Few problems with this component whilst working on the 'News and events' design.

The default usage of the macro results in:

1.  **Empty label attribute** (should be populated with a default label title even if it is hidden using a utility class)

2. **Classes modifier** (should allow flexibility in the width of the input if required. A class is added to the input, however, there is no space between class additions, which causes a bug

We also need to look at the ordering of the classes. The class additions seem to come before the already defined width attribute and therefore would have no effect on the width anyway

3. **Responsive width** (should scale nicely and be full width on mobile. However due to the `flex-flow: row wrap` when the screen is reduced the component breaks. Removing this attribute fixes the issue

4. **Unused classes** (classes have been added that have no effect, and should really be removed)

5. **Enhancements** (adding the option for attributes would be a good improvement)
