### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by ogonkov** [ONSdigital/design-system#689]
**Describe the bug**
Not sure is it bug, but looks like it is. Circular dependency
1. `src/components/checkboxes/_checkbox-macro.njk` imports
2. `src/components/input/_macro.njk` imports
3. `src/components/mutually-exclusive/_macro.njk` imports
4. `src/components/checkboxes/_checkbox-macro.njk`

**To Reproduce**
`yarn test` shows few warnings

**Expected behavior**
Dependencies is not circular

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #689: Circular dependency](https://trello.com/c/DKn2v8RM/696-issue-689-circular-dependency)

**Comment by boxadesign** [comment]
I don't think we can fix this easily.

The issue is a warning when running tests. There's 3 warnings which are all due to the mutually exclusive macro calling the checkbox macro. What happens is:

checkbox _can_ call input -> input _can_ call mutually exclusive -> mutually exclusive _will_ call checkbox

If I remove the checkbox import from mutually exclusive the warning is removed but its a dependency of the component.

Without re-writing the dependency structure of these components I don't think it can be fixed. I don't know if it's fixable with how our components work. If we care enough we may need to re-think things completely.
