### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#716]
Use this issue to discuss [Downloads](https://ons-design-system.netlify.com/components/downloads/) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by trevorsaint** [comment]
**An improvement for this component would be to:**

Add `tabindex="-1"` for the image thumbnail link.

We have an `aria-hidden="true"` attribute, which is great because we don’t want screen readers reading out the link twice.

However a keyboard user would still have to tab twice for the thumbnail link and the heading link.

They do the same thing. Adding `tabindex="-1"` will resolve this.

**Comment by rmccar** [comment]
> **An improvement for this component would be to:**
> 
> Add `tabindex="-1"` for the image thumbnail link.
> 
> We have an `aria-hidden="true"` attribute, which is great because we don’t want screen readers reading out the link twice.
> 
> However a keyboard user would still have to tab twice for the thumbnail link and the heading link.
> 
> They do the same thing. Adding `tabindex="-1"` will resolve this.

Sounds good Ive raised a PR to fix this

**Comment by trevorsaint** [comment]
We need to update the thumbnail path to allow for a smallPath and a largePath.

Currently the macro expects a small and large folder (hardcoded into macro). However, with the way Craft does image modifications it names the folders with an underscore.

Allowing for a smallPath and a largePath would sort this issue out and also make the component more flexible.

**Comment by trevorsaint** [comment]
We need the ability to have a fallback image if no image specified as part of the component.
