### ISSUE TITLE
Table of contents 

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#719]
Use this issue to discuss [Table of Contents ](https://ons-design-system.netlify.com/components/toc/) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by trevorsaint** [comment]
Ensure spacing between each item is consistent.

This bug is due to the extra padding caused when using `display: inline-block` on the link. Adding an attribute `vertical-align: top` will fix this.

Currently this:
![image](https://user-images.githubusercontent.com/4989027/87784326-f6ec8280-c82d-11ea-9535-e8beaf071c21.png)

Should be this:
![image](https://user-images.githubusercontent.com/4989027/87784355-079cf880-c82e-11ea-8f05-ead09fe76da5.png)
